version: "3.7"
services:
  # redis 설정
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # 서버 설정
  backend:
    image: squirmm/campper-prod:main
    container_name: backend
    hostname: backend
    env_file:
      - ./.env
    expose:
      - "8080"

  client:
    image: squirmm/campper-client:main
    container_name: client
    hostname: client
    ports:
      - "3000:3000"

  # nginx 설정
  nginx:
    depends_on:
      - backend
      - client
      - redis
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
